export function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

export function formatDate(timestamp: number): string {
  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  }).format(timestamp);
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text);
}

export function shareVerse(reference: string, text: string, notes?: string): string {
  let shareText = `📖 ${reference}\n\n`;
  shareText += `"${text}"\n\n`;
  
  if (notes) {
    shareText += `💭 Personal Notes:\n${notes}\n\n`;
  }
  
  shareText += `━━━━━━━━━━━━━━━━━━━━\n`;
  shareText += `✨ Shared from Faith Explorer\n`;
  shareText += `Explore sacred texts across faiths\n`;
  shareText += `faithexplorer.app`;
  
  return shareText;
}

export function shareInsight(insightText: string, religionName?: string): string {
  // Strip HTML tags from AI response
  const plainText = insightText.replace(/<[^>]*>/g, '').replace(/\n\n+/g, '\n\n');
  
  let shareText = `💡 AI Insight`;
  if (religionName) {
    shareText += ` - ${religionName}`;
  }
  shareText += `\n\n`;
  shareText += `${plainText}\n\n`;
  shareText += `━━━━━━━━━━━━━━━━━━━━\n`;
  shareText += `✨ Generated by Faith Explorer\n`;
  shareText += `Interfaith wisdom at your fingertips\n`;
  shareText += `faithexplorer.app`;
  
  return shareText;
}

export function shareComparison(analysisText: string, religions: string[]): string {
  // Strip HTML tags
  const plainText = analysisText.replace(/<[^>]*>/g, '').replace(/\n\n+/g, '\n\n');
  
  let shareText = `🌍 Comparative Analysis\n`;
  shareText += `Perspectives from: ${religions.join(', ')}\n\n`;
  shareText += `${plainText}\n\n`;
  shareText += `━━━━━━━━━━━━━━━━━━━━\n`;
  shareText += `✨ Generated by Faith Explorer\n`;
  shareText += `Compare sacred texts across faiths\n`;
  shareText += `faithexplorer.app`;
  
  return shareText;
}

export function getReligionColor(religion: string): string {
  const colors: Record<string, string> = {
    christianity: '#DC2626',
    islam: '#059669',
    judaism: '#2563EB',
    hinduism: '#D97706',
    buddhism: '#7C3AED',
    sikhism: '#EA580C',
    taoism: '#0891B2',
    confucianism: '#BE123C',
    shinto: '#DB2777',
  };
  return colors[religion] || '#6B7280';
}
